### ISSUE TITLE
al escaneear el Qr me aparece esto

### ISSUE THREAD

**Issue by daimoxd** [shanduy/ShanBot#22]
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

que puedo hacer

**Comment by shanduy** [comment]
> node:internal/errors:464 ErrorCaptureStackTrace(err); ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined at new NodeError (node:internal/errors:371:5) at prepareSecretKey (node:internal/crypto/keys:570:11) at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9) at new Cipheriv (node:internal/crypto/cipher:243:3) at Object.createCipheriv (node:crypto:138:10) at Object.aesEncrypt (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24) at WAConnection.sendBinary (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26) at WAConnection. (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18) at WAConnection.emit (node:events:402:35) at WAConnection.emit (/data/data/com.termux/files/home/ShanBot/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) { code: 'ERR_INVALID_ARG_TYPE' }
> 
> que puedo hacer
